server:
  port: 5001
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/testkeystore.p12
    key-store-password: password

org:
  simpleLogger:
    showDateTime: true

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        connection:
          driver_class: com.mysql.jdbc.Driver
        c3po:
          min_size: 1
          max_size: 20
          timeout: 1500
          max_statements: 50

  datasource:
    url: jdbc:mysql://localhost:3306/rms_db
    username: rms-api
    password: rmsapipassword

springdoc:
  swagger-ui:
    path: /swagger-ui.html